language: go
go: 
 - 1.9.x
 - 1.10.x

install:
 - go get -v
 - go get -v github.com/bitly/go-simplejson
 - go get -v github.com/fatih/color
 - go get -u github.com/alecthomas/gometalinter
script:
 - gometalinter --install
 - gometalinter --config=./gometalinter.json --vendor ./...
 - cp ./config_sample.json ./config.json
 - go test -v ./...
